version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/pr-diff-bot"
    schedule:
      interval: "weekly"
    groups:
      python-packages:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      github-actions:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
