version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/pr-diff-bot"
    schedule:
      interval: "weekly"
    groups:
      python-packages:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
    # Enable auto-merge for Python packages
    auto-merge: true
    # Only merge if tests pass
    auto-merge-conditions:
      - "status-success=build"
    # Create a version bump PR for Python dependencies
    version-update-type: "bump-patch"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      github-actions:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
    # Enable auto-merge for GitHub Actions updates
    auto-merge: true
    # Only merge if tests pass
    auto-merge-conditions:
      - "status-success=build"
    # Don't create version bumps for GitHub Actions updates
    version-update-type: "none"
