version: 2
updates:
  # Python dependencies
  - package-ecosystem: "pip"
    directory: "/pr-diff-bot"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "fix"
      prefix-development: "chore"
      include: "scope"
    labels:
      - "dependencies"
      - "python"
    open-pull-requests-limit: 10

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "ci"
      include: "scope"
    labels:
      - "dependencies"
      - "github-actions"
    open-pull-requests-limit: 10
