version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/pr-diff-bot"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "America/Los_Angeles"
    groups:
      python-packages:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
    commit-message:
      prefix: "fix"
      include: "scope"
    labels:
      - "dependencies"
      - "python"
    open-pull-requests-limit: 10
    rebase-strategy: "auto"
    target-branch: "main"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "America/Los_Angeles"
    groups:
      github-actions:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
    commit-message:
      prefix: "fix"
      include: "scope"
    labels:
      - "dependencies"
      - "github-actions"
    open-pull-requests-limit: 10
    rebase-strategy: "auto"
    target-branch: "main"
