version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/pr-diff-bot"
    schedule:
      interval: "weekly"
    groups:
      python-packages:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
    # Configure version updates
    versioning-strategy: increase
    # Configure PR settings
    open-pull-requests-limit: 10
    rebase-strategy: "auto"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      github-actions:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
    # Configure PR settings
    open-pull-requests-limit: 10
    rebase-strategy: "auto"
