name: "PR Diff Analyzer"
description: "Analyzes pull request changes and provides AI-powered code review comments"
author: "PR Diff Bot"

inputs:
  github_token:
    description: "GitHub token for API access"
    required: true
  openrouter_key:
    description: "OpenRouter API key for AI analysis"
    required: true

runs:
  using: "docker"
  image: "Dockerfile"
  env:
    GITHUB_TOKEN: ${{ inputs.github_token }}
    OPENROUTER_API_KEY: ${{ inputs.openrouter_key }}
    REPOSITORY: ${{ github.repository }}
    PR_NUMBER: ${{ github.event.pull_request.number }}
    MODEL: "anthropic/claude-3.5-sonnet"
  args:
    - ${{ github.repository }}
    - ${{ github.event.pull_request.number }}
    - "--model"
    - "anthropic/claude-3.5-sonnet"
