name: "PR Diff Analyzer"
description: "Analyzes pull request changes and provides AI-powered code review comments"
author: "PR Diff Bot"

inputs:
  github_token:
    description: "GitHub token for API access"
    required: true
  openrouter_key:
    description: "OpenRouter API key for AI analysis"
    required: true
  repository:
    description: "Repository name in format owner/repo"
    required: true
  pull_request_number:
    description: "Pull request number to analyze"
    required: true
  model:
    description: "OpenRouter model to use for analysis"
    required: false
    default: "anthropic/claude-3.5-sonnet"

runs:
  using: "docker"
  image: "docker://ghcr.io/${{ github.repository }}:v1"
  env:
    GITHUB_TOKEN: ${{ inputs.github_token }}
    OPENROUTER_API_KEY: ${{ inputs.openrouter_key }}
  args:
    - ${{ inputs.repository }}
    - ${{ inputs.pull_request_number }}
    - --model
    - ${{ inputs.model }}
