[tool.semantic_release]
version_variable = "pr-diff-bot/__init__.py:__version__"
branch = "main"
upload_to_pypi = false
upload_to_release = true
build_command = ""
commit_message = "chore(release): {version}"
commit_parser = "angular"
changelog_components = "semantic_release.changelog.changelog"
changelog_file = "CHANGELOG.md"
# Configure version bumping
major_on_zero = true
patch_without_tag = true
version_source = "commit"

[tool.semantic_release.branches.main]
match = "main"
prerelease = false

[tool.semantic_release.branches.release]
match = "release-*"
prerelease = false

# Configure commit types that trigger releases
[tool.semantic_release.commit_parser_options]
allowed_tags = ["feat", "fix", "perf"]
minor_tags = ["feat"]
patch_tags = ["fix", "perf"]

# Configure commit parsing
[tool.semantic_release.parser_angular.allowed_types]
fix = "patch"
perf = "patch"
feat = "minor"