[tool.semantic_release]
version_variable = "pr-diff-bot/__init__.py:__version__"
branch = "main"
upload_to_pypi = false
upload_to_release = true
build_command = ""  # Empty string instead of false
commit_message = "chore(release): {version}"
commit_parser = "angular"
changelog_components = "semantic_release.changelog.changelog"
changelog_file = "CHANGELOG.md"
# Configure release branches
[tool.semantic_release.branches.main]
match = "main"
prerelease = false

[tool.semantic_release.branches.release]
match = "release-*"
prerelease = false

# Disable pushing to main branch
push_to_branch = false