[tool.semantic_release]
version_variable = "pr-diff-bot/__init__.py:__version__"
branch = "main"
upload_to_pypi = false
upload_to_release = true
build_command = ""  # Empty string instead of false
commit_message = "chore(release): {version}"
commit_parser = "angular"
changelog_components = "semantic_release.changelog.changelog"
changelog_file = "CHANGELOG.md"
# Allow releases from main and release branches
branches = [
    "main",
    "release-+([0-9])?(.{+([0-9]),x}).x",
    "+([0-9])?(.{+([0-9]),x}).x",
    "release-+([0-9])?(.{+([0-9]),x}).x.+([0-9])",
]
# Disable pushing to main branch
push_to_branch = false