name: PR Analysis
on:
  pull_request:
    types: [opened, synchronize]
    # Optional: Specify paths to analyze
    # paths:
    #   - '**.py'
    #   - '**.js'
    #   - '**.ts'

jobs:
  analyze:
    runs-on: ubuntu-latest
    permissions:
      # Required for PR comments
      pull-requests: write
      # Required for accessing repository contents
      contents: read

    steps:
      - name: PR Diff Analysis
        uses: sudo-whodo/pr-genius@v1
        env:
          # Required: Personal Access Token with PR write permissions
          # Note: GITHUB_TOKEN doesn't have sufficient permissions for PR comments
          # Create a PAT with 'repo' and 'pull_requests' scopes
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}

          # Required: Your OpenRouter API key
          # Get one at: https://openrouter.ai/
          OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}

          # Optional: Override default model
          # MODEL: "anthropic/claude-2"
