name: PR Analysis
on:
  pull_request:
    types: [opened, synchronize]

jobs:
  analyze:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: PR Diff Analysis
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
          OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
        uses: ./
        with:
          github_token: ${{ secrets.PAT_TOKEN }}
          openrouter_key: ${{ secrets.OPENROUTER_API_KEY }}
